version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/LosAngeles
    volumes:
      - "/fast/hass/home-assistant/media:/media"
      - "/home/hass/home-assistant/config:/config"
      - "/home/hass/home-assistant/db:/config/db"
      - "/home/hass/home-assistant/logs:/config/logs"
    ports:
      - 8123:8123 #optional
    #devices:
    #  - /path/to/device:/path/to/device #optional
    restart: unless-stopped
