version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/LosAngeles
    volumes:
      - "/fast/docker/home-assistant/media:/media"
      - "/home/docker/home-assistant/config:/config"
      - "/home/docker/home-assistant/db:/config/db"
      - "/home/docker/home-assistant/logs:/config/logs"
    ports:
      - 8123:8123
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - "/home/docker/mosquitto/config/:/mosquitto/config/:ro"
      - "/home/docker/mosquitto/log/:/mosquitto/log/"
      - "/home/docker/mosquitto/data/:/mosquitto/data/"
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - "/home/docker/zigbee2mqtt/data:/app/data"
      - "/run/udev:/run/udev:ro"
    ports:
      - 8080:8080
    environment:
      - TZ=America/LosAngeles
    #devices:
      # Make sure this matched your adapter location
      #- /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B0018ED3DDF-if00:/dev/ttyACM0

  appdaemon:
    image: hazard/appdaemon-apps:latest
    links:
      - homeassistant
    volumes:
      - "/home/docker/appdaemon/compose/apps:/apps"
    environment:
      - TZ=America/LosAngeles
      - HA_URL=http://homeassistant:8123
      - HA_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI1ZjEzZTZkNDMwNmE0ZmUwODJmOTI4OTRmMzc5YTI2ZiIsImlhdCI6MTU0NTg5NTAwOCwiZXhwIjoxODYxMjU1MDA4fQ.RdSg11mDT1PNIlA72K-01DKPRCCFnuroj-C2AwehI4E
    container_name: "appdaemon"
